Mission04_koletonm/Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_koletonm.Models
{
    public class GradeCalcModel
    {
        [Required]
        [Range(0, 100)]
        public int Assignments { get; set; }
        [Required]
        [Range(0, 100)]
        public int Group { get; set; }
        [Required]
        [Range(0, 100)]
        public int Quizzes { get; set; }
        [Required]
        [Range(0, 100)]
        public int Midterm { get; set; }
        [Required]
        [Range(0, 100)]
        public int Final { get; set; }
        [Required]
        [Range(0, 100)]
        public int Intex { get; set; }

    }
}

Mission04_koletonm/Controllers/GradesController.cs
using Microsoft.AspNetCore.Mvc;
using Mission04_koletonm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_koletonm.Controllers
{
    public class GradesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GradeCalc()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GradeCalc(GradeCalcModel model)
        {
            return View();
        }
    }
}

Mission04_koletonm/Views/Grades/GradeCalc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}

@model GradeCalcModel;

<!--
    Created by: Koleton Murray
    Mission  - Grade Calculator to MVC
-->

<!-- Grade Calculator form -->
<h1>Grade Calculator</h1>
<br />
<p>
    Please enter the percentage scored for each grade category in the form below<br />
    For example: 95.5 or 82
</p>
<form method="post">
    <label>Assignments: </label>
    <input id="assignments" asp-for="Assignments" /><br />

    <label>Group Project: </label>
    <input id="group" asp-for="Group" /><br />

    <label>Quizzes: </label>
    <input id="quizzes" asp-for="Quizzes"/><br />

    <label>Midterm Exam: </label>
    <input id="midterm" asp-for="Midterm"/><br />

    <label>Final Exam: </label>
    <input id="final" asp-for="Final"/><br />

    <label>INTEX: </label>
    <input id="intex" asp-for="Intex"/><br />
    <br />

    <input style="width: 250px;" type="submit" id="btnSend" value="Calculate My Grade" /> <br /> <br />

    <div asp-validation-summary="All"></div>
</form>

<br />
<br />
<br />
<br />
<br />

Mission04_koletonm/Views/Grades/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "About Me";
}

<!--
    Created by: Koleton Murray
    Mission  - Grade Calculator to MVC
-->

<!-- Info about me and IS -->
<h1>Koleton Murray</h1>
<br />
<img src="img/IMG_0699.jpg" title="Koleton loves hiking!" />
<br /><br />
<p>IS 413 is going to be a great class! I'm really excited to get exposure to C#. Learning a strongly typed language will be good for me in the long run even if it is a bit frustrating. I'm also excited to work within the ASP.NET framework. I think it will be great experience to make me an even more well rounded programmer.</p>
<br />
<h3>My top 3 post-graduation job fields:</h3>
<ul>
    <li>Development</li>
    <li>Analytics</li>
    <li>Secruity</li>
</ul>
<br />

Mission04_koletonm/Views/Shared/_Layout.cshtml
<!--
    Created by: Koleton Murray
    Mission  - Grade Calculator to MVC
-->

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>

    <!-- Adds an icon in the tab bar for my site-->
    <link rel="icon" href="~/img/book-stack.png">

    <!-- Adds the bootstrap and then my own css to style my site -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/myStyle.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="Grades" asp-action="Index">Home (About Me)</a>
        <a asp-controller="Grades" asp-action="GradeCalc">Grade Calculator</a>
    </nav>
    <br />
    <div>
        @RenderBody()
    </div>

    <!-- Credit the icon author so I don't get in trouble -->
    <a href="https://www.flaticon.com/free-icons/book" title="book icons">Book icons created by Freepik - Flaticon</a>

    <!-- js scripts to work with bootstrap and then work with the form to calcualte the grade -->
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/js/calculator.js"></script>
</body>
</html>